name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - uses: fish-actions/install-fish@v1
      - run: make lint
      - run: make test
        env:
          TERM: xterm-256color
